### ISSUE TITLE
Some comments within interface blocks produce errors

### ISSUE THREAD

**Issue by jme52** [camfort/fortran-src#61]
Comments within interface blocks sometimes produce errors.  After some testing, it looks like comments in the first line of the block may work OK, but comments in other lines produce errors.

Example: when attempting to process file
```
module ic

   interface s
      module procedure a
      !
   end interface

contains

   subroutine a
      write(*,*) 'A'
   end subroutine

end module ic
```
with camfort 0.905 + fortran-src 0.2.1.1, the following error is returned:
```
$ stack exec camfort count ic.f90 
Counting variable declarations in 'ic.f90'
ic.f90, 5:8: ic.f90: parsing failed. 
Last parsed token: TComment (5:7)-(5:7) "".
```

**Comment by mrd** [comment]
I believe this has been fixed as of December but I neglected to close this bug.

**Comment by jme52** [comment]
The case above is indeed fixed - thank you.

However, there are two interface comment cases which unfortunately are still broken: comments at the `interface` and `end interface` lines.  E.g., files

```
module ic

   interface s !
      module procedure a
   end interface

contains

   subroutine a
      write(*,*) 'A'
   end subroutine

end module ic
```
and
```
module ic

   interface s
      module procedure a
   end interface !

contains

   subroutine a
      write(*,*) 'A'
   end subroutine

end module ic
```
result, respectively, in 
```
$ stack exec camfort -- count -F95 ic2.f90
Getting project config file from STACK_YAML environment
Counting variable declarations in 'ic2.f90'
Successfully parsed 0 precompiled file(s).
ic2.f90, 3:17: ic2.f90: parsing failed. 
Last parsed token: TComment (3:16)-(3:16) "".
```
and
```
$ stack exec camfort -- count -F95 ic3.f90
Getting project config file from STACK_YAML environment
Counting variable declarations in 'ic3.f90'
Successfully parsed 0 precompiled file(s).
ic3.f90, 5:19: ic3.f90: parsing failed. 
Last parsed token: TComment (5:18)-(5:18) "".
```
I am using fortran-src edd454e9 (with camfort/camfort@fd67ba04).

**Comment by jme52** [comment]
Thank you, the fix works for my code.
